#application: annalect-api-jobs
#version: v1-multiapi
runtime: php55
api_version: 1
service: api-extractor
instance_class: B4
basic_scaling:
  max_instances: 10
  idle_timeout: 40m

handlers:
- url: /_ah/start
  script: start.php
  secure: always

- url: /run
  script: run.php
  secure: always

- url: /run-tasks
  script: tasker.php
  secure: always

- url: /edit
  script: edit.php
  secure: always