#application: annalect-api-jobs
#service: api-extractor-staging
service: api-extractor
#version: v1

runtime: php55
api_version: 1

# Using B4_1G because need more memory for replace csv files
# Todo change to B2 reducing resource

instance_class: B4_1G
basic_scaling:
  max_instances: 25
  idle_timeout: 10m

handlers:
- url: /_ah/start
  script: start.php
  secure: always

- url: /(.+\.(ico|jpg|png|gif|woff2|ttf|svg))$
  static_files: \1
  upload: (.+\.(ico|jpg|png|gif|woff2|ttf|svg))$
  expiration: "365d"

- url: /(.+\.(htm|html|css|js|svg))$
  static_files: \1
  upload: (.+\.(htm|html|css|js|svg))$
  expiration: "365d"
  application_readable: true


- url: /
  script: index.php
  secure: always

- url: /save-config
  script: save-config.php
  secure: always

- url: /run
  script: run.php
  secure: always

- url: /log
  script: log.php
  secure: always

- url: /run-tasks-.+
  script: tasker.php
  secure: always

- url: /run-bigquery
  script: run-bigquery.php
  secure: always

- url: /run-bigquery-std
  script: run-bigquery-std.php
  secure: always

- url: /run-talendjob
  script: run-talendjob.php
  secure: always

- url: /run-virtualmachine
  script: run-virtualmachine.php
  secure: always

- url: /run-append-to-output
  script: run-append-to-output.php
  secure: always

- url: /run-moat
  script: run-moat.php
  secure: always

- url: /run-moat-batch
  script: run-moat-batch.php
  secure: always


- url: /test
  script: test.php
  secure: always

- url: /test2
  script: test2.php
  secure: always
