application: annalect-api-jobs
version: v1-multiapi
runtime: php55
api_version: 1
service: api-jobs
instance_class: B4
basic_scaling:
  max_instances: 10
  idle_timeout: 40m

handlers:

- url: /
  script: index.php
  secure: always

- url: /run
  script: tasker.php
  secure: always

- url: /edit
  script: edit.php
  secure: always