#application: annalect-api-jobs
service: api-extractor
#version: v1

runtime: php55
api_version: 1

# Using B4_1G because need more memory for replace csv files
# Todo change to B2 reducing resource

instance_class: B4_1G
basic_scaling:
  max_instances: 10
  idle_timeout: 40m

handlers:
- url: /_ah/start
  script: start.php
  secure: always

- url: /
  script: index.php
  secure: always

- url: /run
  script: run.php
  secure: always

- url: /run-tasks
  script: tasker.php
  secure: always

- url: /edit
  script: edit.php
  secure: always

- url: /test
  script: test.php
  secure: always

- url: /test2
  script: test2.php
  secure: always